openapi: 3.0.3
info:
  title: MultiStockBack-MercadoLibre
  description: This document provides a detailed reference for the MercadoLibre API, listing all available endpoints, their respective HTTP methods, expected request parameters, and response formats. This guide is intended to assist front-end developers in integrating MercadoLibre services efficiently.
  version: 1.0.0
servers:
  - url: https://linen-anteater-319357.hostingersite.com/api
paths: {}
